<a href="https://colab.research.google.com/github/NishchayBhardwaj/DSML/blob/main/AllAIAssignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1) Assignment-1**

**BFS Approach**

In [ ]:
import numpy as np

def bfs(src, target):
  queue = []
  queue.append(src)

  exp = []
  while len(queue) > 0:
    source = queue.pop(0)
    exp.append(source)

    print_state(source)

    if source == target:
      print()
      print("Success! Goal state achieved.")

      return

    poss_moves_to_do = possible_moves(source, exp)

    for move in poss_moves_to_do:
      if move not in exp and move not in queue:
        queue.append(move)

In [ ]:
def possible_moves(state, visited_state):
  emp_tile = state.index(0)

  d = []

  if emp_tile not in [0,1,2]:
    d.append('u')
  if emp_tile not in [6,7,8]:
    d.append('d')
  if emp_tile not in [0,3,6]:
    d.append('l')
  if emp_tile not in [2,5,8]:
    d.append('r')

  poss_moves_it_can = []

  for i in d:
    poss_moves_it_can.append(gen(state, i, emp_tile))

  return[move_it_can for move_it_can in poss_moves_it_can if move_it_can not in visited_state]

In [ ]:
def gen(state, m, emp_tile):
  temp = state.copy()

  if m == 'd':
    temp[emp_tile + 3], temp[emp_tile] = temp[emp_tile], temp[emp_tile + 3]
  if m == 'u':
    temp[emp_tile - 3], temp[emp_tile] = temp[emp_tile], temp[emp_tile - 3]
  if m == 'l':
    temp[emp_tile - 1], temp[emp_tile] = temp[emp_tile], temp[emp_tile - 1]
  if m == 'r':
    temp[emp_tile + 1], temp[emp_tile] = temp[emp_tile], temp[emp_tile + 1]

  return temp

In [ ]:
def print_state(state):
  print(np.array(state).reshape(3,3))
  print()

src = [0, 2, 3, 1, 8, 4, 7, 5, 6]
target = [1, 2, 3, 4, 0, 5, 6, 7, 8]

print("Initial State:")
print_state(src)

print("\nGoal State:")
print_state(target)

print("\nBFS Solution:")
bfs(src, target)

Streaming output truncated to the last 5000 lines.
 [5 8 1]]

[[2 1 7]
 [5 6 3]
 [0 8 4]]

[[2 1 7]
 [5 6 3]
 [8 4 0]]

[[0 1 7]
 [2 5 3]
 [8 6 4]]

[[2 1 7]
 [8 5 3]
 [0 6 4]]

[[2 1 0]
 [5 3 7]
 [8 6 4]]

[[2 1 7]
 [5 3 4]
 [8 6 0]]

[[5 2 7]
 [8 1 3]
 [0 6 4]]

[[5 2 7]
 [1 0 3]
 [8 6 4]]

[[5 2 3]
 [8 7 1]
 [0 6 4]]

[[5 2 3]
 [7 0 1]
 [8 6 4]]

[[2 3 1]
 [5 7 4]
 [8 6 0]]

[[2 3 1]
 [5 0 7]
 [8 6 4]]

[[0 7 3]
 [2 6 1]
 [5 8 4]]

[[2 7 3]
 [6 0 1]
 [5 8 4]]

[[7 5 3]
 [2 0 1]
 [8 6 4]]

[[7 3 0]
 [2 5 1]
 [8 6 4]]

[[2 7 3]
 [8 0 1]
 [6 5 4]]

[[2 7 3]
 [8 5 1]
 [6 4 0]]

[[4 8 7]
 [2 0 3]
 [1 5 6]]

[[4 7 0]
 [2 8 3]
 [1 5 6]]

[[2 8 4]
 [1 0 7]
 [5 6 3]]

[[0 2 4]
 [1 8 7]
 [5 6 3]]

[[0 2 7]
 [1 4 8]
 [5 6 3]]

[[2 7 0]
 [1 4 8]
 [5 6 3]]

[[2 4 7]
 [1 6 8]
 [0 5 3]]

[[2 4 7]
 [1 6 8]
 [5 3 0]]

[[0 4 7]
 [2 1 8]
 [5 6 3]]

[[2 4 7]
 [5 1 8]
 [0 6 3]]

[[4 1 7]
 [2 8 3]
 [0 5 6]]

[[4 1 7]
 [2 8 3]
 [5 6 0]]

[[4 1 7]
 [5 2 3]
 [0 8 6]]

[[4 1 0]
 [2 3 7]
 [5 8 6]]

[[4 1 7]
 

**DFS Approach**

In [ ]:
import numpy as np

def dfs(src, target):
  stack = []
  stack.append(src)

  exp = []
  while len(stack) > 0:
    source = stack.pop()
    exp.append(source)

    print_state(source)

    if source == target:
      print()
      print("Success! Goal state achieved.")

      return

    poss_moves_to_do = possible_moves(source, exp)

    for move in poss_moves_to_do:
      if move not in exp and move not in stack:
        stack.append(move)

In [ ]:
def possible_moves(state, visited_state):
  emp_tile = state.index(0)

  d = []

  if emp_tile not in [0,1,2]:
    d.append('u')
  if emp_tile not in [6,7,8]:
    d.append('d')
  if emp_tile not in [0,3,6]:
    d.append('l')
  if emp_tile not in [2,5,8]:
    d.append('r')

  poss_moves_it_can = []

  for i in d:
    poss_moves_it_can.append(gen(state, i, emp_tile))

  return[move_it_can for move_it_can in poss_moves_it_can if move_it_can not in visited_state]

In [ ]:
def gen(state, m, emp_tile):
  temp = state.copy()

  if m == 'd':
    temp[emp_tile + 3], temp[emp_tile] = temp[emp_tile], temp[emp_tile + 3]
  if m == 'u':
    temp[emp_tile - 3], temp[emp_tile] = temp[emp_tile], temp[emp_tile - 3]
  if m == 'l':
    temp[emp_tile - 1], temp[emp_tile] = temp[emp_tile], temp[emp_tile - 1]
  if m == 'r':
    temp[emp_tile + 1], temp[emp_tile] = temp[emp_tile], temp[emp_tile + 1]

  return temp

In [ ]:
def print_state(state):
  print(np.array(state).reshape(3,3))
  print()

src = [0, 2, 3, 1, 8, 4, 7, 5, 6]
target = [1, 2, 3, 4, 0, 5, 6, 7, 8]

print("Initial State:")
print_state(src)

print("\nGoal State:")
print_state(target)

print("\nBFS Solution:")
dfs(src, target)

Streaming output truncated to the last 5000 lines.
 [5 3 8]]

[[6 4 2]
 [5 0 7]
 [3 1 8]]

[[6 4 2]
 [5 7 0]
 [3 1 8]]

[[6 4 2]
 [5 7 8]
 [3 1 0]]

[[6 4 2]
 [5 7 8]
 [3 0 1]]

[[6 4 2]
 [5 7 8]
 [0 3 1]]

[[6 4 2]
 [0 7 8]
 [5 3 1]]

[[6 4 2]
 [7 0 8]
 [5 3 1]]

[[6 4 2]
 [7 8 0]
 [5 3 1]]

[[6 4 2]
 [7 8 1]
 [5 3 0]]

[[6 4 0]
 [7 8 2]
 [5 3 1]]

[[6 0 4]
 [7 8 2]
 [5 3 1]]

[[0 6 4]
 [7 8 2]
 [5 3 1]]

[[7 6 4]
 [0 8 2]
 [5 3 1]]

[[7 6 4]
 [8 0 2]
 [5 3 1]]

[[7 6 4]
 [8 2 0]
 [5 3 1]]

[[7 6 4]
 [8 2 1]
 [5 3 0]]

[[7 6 4]
 [8 2 1]
 [5 0 3]]

[[7 6 4]
 [8 2 1]
 [0 5 3]]

[[7 6 4]
 [0 2 1]
 [8 5 3]]

[[7 6 4]
 [2 0 1]
 [8 5 3]]

[[7 6 4]
 [2 1 0]
 [8 5 3]]

[[7 6 4]
 [2 1 3]
 [8 5 0]]

[[7 6 4]
 [2 1 3]
 [8 0 5]]

[[7 6 4]
 [2 1 3]
 [0 8 5]]

[[7 6 4]
 [0 1 3]
 [2 8 5]]

[[7 6 4]
 [1 0 3]
 [2 8 5]]

[[7 6 4]
 [1 3 0]
 [2 8 5]]

[[7 6 4]
 [1 3 5]
 [2 8 0]]

[[7 6 4]
 [1 3 5]
 [2 0 8]]

[[7 6 4]
 [1 3 5]
 [0 2 8]]

[[7 6 4]
 [0 3 5]
 [1 2 8]]

[[7 6 4]
 [3 0 5]
 [1 2 8]]

[[7 6 4]
 

# **Assignment-2**

**Missionaries and Cannibals Problem**

In [ ]:
class MissionaryCannibal:
  def __init__(self):
    self.left = [3,3,1]
    self.right = [0,0,0]

  def display_state(self):
    print(f"Left Side: {self.left[0]} Missionaries, {self.left[1]} Cannibals, Boat: {'Yes' if self.left[2] == 1 else 'No'}")
    print(f"Right Side: {self.right[0]} Missionaries, {self.right[1]} Cannibals, Boat: {'Yes' if self.right[2] == 1 else 'No'}")

  def move(self, missionaries, cannibals, to_right):
    if (missionaries + cannibals > 2) or missionaries < 0 or cannibals < 0 or (missionaries == 0 and cannibals == 0):
      return False

    if to_right:
      if self.left[0] >= missionaries and self.left[1] >= cannibals and self.left[2] == 1:
        self.left[0] -= missionaries
        self.left[1] -= cannibals
        self.right[0] += missionaries
        self.right[1] += cannibals
        self.left[2] = 0
        self.right[2] = 1
        return True

    else:
      if self.right[0] >= missionaries and self.right[1] >= cannibals and self.right[2] == 1:
        self.right[0] -= missionaries
        self.right[1] -= cannibals
        self.left[0] += missionaries
        self.left[1] += cannibals
        self.right[2] = 0
        self.left[2] = 1
        return True

  def win(self):
    if self.right[0] == 3 and self.right[1] == 3:
      return True
    return False

  def check_lose(self):
    if (self.left[0] > 0 and self.left[1] > self.left[0]) or (self.right[0] > 0 and self.right[1] > self.right[0]):
      return True
    return False

def main():
  game = MissionaryCannibal()

  while(True):
    game.display_state()

    if game.win():
      print("Congratulations! All missionaries and cannibals have successfully crossed the river.")
      break

    if game.check_lose():
      print("You lose. Cannibals outnumbered missionaries on one side.")
      break

    try:
      missionaries = int(input("Enter number of missionaries to move: "))
      cannibals = int(input("Enter number of cannibals to move: "))

    except ValueError:
      print("Invalid input. Please enter integers.")
      continue

    to_right = game.left[2] == 1

    if not game.move(missionaries, cannibals, to_right):
      print("Invalid move. Try again.")

if __name__ == "__main__":
  main()

**Color Map**

In [ ]:
def is_safe(graph, color, colors, assigned_colors, vertex):
  for i in range(len(graph)):
    if graph[vertex][i] == 1 and assigned_colors[i] == color:
      return False
  return True

def print_assignment(assigned_colors, step):
  print(f"Step {step}: {assigned_colors}.")

def map_coloring(graph, colors, assigned_colors, vertex, step):
  if vertex == len(graph):
    return True

  for color in colors:
    if is_safe(graph, color, colors, assigned_colors, vertex):
      assigned_colors[vertex] = color
      print_assignment(assigned_colors, step)
      step += 1

      if map_coloring(graph, colors, assigned_colors, vertex + 1, step):
        return True

      assigned_colors[vertex] = None
      print(f"Backtrack from step {step}")

  return False

def solve_map_coloring(graph, colors):
  assigned_colors = [None] * len(graph)
  step = 1

  if not map_coloring(graph, colors, assigned_colors, 0, step):
    return None

  return assigned_colors

graph = [
    [0, 1, 0, 0, 1],
    [1, 0, 1, 1, 0],
    [1, 1, 0, 1, 1],
    [0, 1, 1, 0, 1],
    [1, 0, 1, 1, 0]
]

colors = ['Red', 'Green', 'Yellow']

solution = solve_map_coloring(graph, colors)

if solution:
  print(f"\nFinal Solution: {solution}")

Step 1: ['Red', None, None, None, None].
Step 2: ['Red', 'Green', None, None, None].
Step 3: ['Red', 'Green', 'Yellow', None, None].
Step 4: ['Red', 'Green', 'Yellow', 'Red', None].
Step 5: ['Red', 'Green', 'Yellow', 'Red', 'Green'].

Final Solution: ['Red', 'Green', 'Yellow', 'Red', 'Green']


# **Assignment - 3**

In [ ]:
!apt-get install swi-prolog
!pip install pyswip

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  autopoint debhelper debugedit dh-autoreconf dh-strip-nondeterminism dwz gettext gettext-base
  intltool-debian libarchive-cpio-perl libarchive-zip-perl libdebhelper-perl
  libfile-stripnondeterminism-perl libmail-sendmail-perl libossp-uuid16 libsub-override-perl
  libsys-hostname-long-perl libtool po-debconf swi-prolog-core swi-prolog-core-packages
  swi-prolog-doc swi-prolog-nox swi-prolog-x
Suggested packages:
  dh-make gettext-doc libasprintf-dev libgettextpo-dev uuid libtool-doc gcj-jdk libmail-box-perl
  elpa-ediprolog swi-prolog-java swi-prolog-odbc swi-prolog-bdb
The following NEW packages will be installed:
  autopoint debhelper debugedit dh-autoreconf dh-strip-nondeterminism dwz gettext gettext-base
  intltool-debian libarchive-cpio-perl libarchive-zip-perl libdebhelper-perl
  libfile-stripnondeterminism-perl libmail-sendmail-p

In [ ]:
from pyswip import Prolog

prolog = Prolog()

# Define gender facts(male and female)
prolog.assertz("male(john)")
prolog.assertz("male(tom)")
prolog.assertz("male(lucas)")
prolog.assertz("female(mary)")
prolog.assertz("female(sarah)")
prolog.assertz("female(kate)")
prolog.assertz("female(lily)")

In [ ]:
# Define family relationships(family facts)

prolog.assertz("parent(john, sarah)")
prolog.assertz("parent(john, tom)")
prolog.assertz("parent(mary, sarah)")
prolog.assertz("parent(mary, tom)")
prolog.assertz("parent(sarah, kate)")
prolog.assertz("parent(sarah, lucas)")
prolog.assertz("parent(tom, lily)")

In [ ]:
# Define rules for family relationships

prolog.assertz("sibling(X, Y) :- parent(P, X), parent(P, Y), X \\= Y")

prolog.assertz("grandparent(X, Y) :- parent(X, Z), parent(Z, Y)")

prolog.assertz("mother(X, Y) :- parent(X, Y), female(X)")

prolog.assertz("father(X, Y) :- parent(X, Y), male(X)")

prolog.assertz("grandmother(X, Y) :- mother(X, Z), parent(Z, Y)")

prolog.assertz("grandfather(X, Y) :- father(X, Z), parent(Z, Y)")

In [ ]:
# Queries
# Query - 1: Sarah's siblings

print("Sarah's Siblings: ")
siblings = list(prolog.query("setof(Sibling, sibling(sarah, Sibling), SiblingList)"))
if siblings:
  for sibling in siblings[0]['SiblingList']:
    print(sibling)

Sarah's Siblings: 
tom


In [ ]:
# Query - 2: Kate's Grandparents

print("\nKate's Grandparents: ")
grandparents = list(prolog.query("setof(Grandparent, grandparent(Grandparent, kate), GrandparentList)"))
if grandparents:
  for grandparent in grandparents[0]['GrandparentList']:
    print(grandparent)


Kate's Grandparents: 
john
mary


In [ ]:
# Query - 3: Tom's children

print("\nTom's children: ")
children = list(prolog.query("setof(Child, parent(tom, Child), ChildList)"))
if children:
  for child in children[0]['ChildList']:
    print(child)


Tom's children: 
lily


In [ ]:
# Query - 4: Kate's Father

print("\nKate's Father: ")
for result in prolog.query("father(Father, kate)"):
  print(result['Father'])


Kate's Father: 


In [ ]:
# Query - 5: Kate's Mother

print("\nKate's Mother: ")
for result in prolog.query("mother(Mother, kate)"):
  print(result['Mother'])


Kate's Mother: 
sarah


In [ ]:
# Query - 6: Kate's grandfather

print("\nKate's grandfather: ")
grandfathers = list(prolog.query("setof(Grandfather, grandfather(Grandfather, kate), GrandfatherList)"))
if grandfathers:
  for grandfather in grandfathers[0]['GrandfatherList']:
    print(grandfather)


Kate's grandfather: 
john


In [ ]:
# Query - 7: Kate's grandmother

print("\nKate's grandmother: ")
grandmothers = list(prolog.query("setof(Grandmother, grandmother(Grandmother, kate), GrandmotherList)"))
if grandmothers:
  for grandmother in grandmothers[0]['GrandmotherList']:
    print(grandmother)


Kate's grandmother: 
mary


# **Assignment - 4**

In [ ]:
import math
import heapq

class Cell:
  def __init__(self):
    self.parent_i = 0
    self.parent_j = 0
    self.f = float('inf')
    self.g = float('inf')
    self.h = 0

ROW = 9
COL = 10

def is_valid(row, col):
  return (row >= 0) and (row < ROW) and (col >= 0) and (col < COL)

def is_unblocked(grid, row, col):
  return grid[row][col] == 1

def is_destination(row, col, dest):
  return (row == dest[0]) and (col == dest[1])

def calculate_h_value(row, col, dest):
  return ((row - dest[0]) ** 2 + (col - dest[1]) ** 2) ** 0.5



def trace_path(cell_details, dest):
  print("The Path is: ")
  path = []
  row = dest[0]
  col = dest[1]

  while not (cell_details[row][col].parent_i == row and cell_details[row][col].parent_j == col):
    path.append((row, col))
    temp_row = cell_details[row][col].parent_i
    temp_col = cell_details[row][col].parent_j
    row = temp_row
    col = temp_col

  path.append((row, col))
  path.reverse()

  for i in path:
    print("->", i, end=" ")
  print()

def a_star_search(grid, src, dest):

  if not is_valid(src[0], src[1]) or not is_valid(dest[0], dest[1]):
    print("Source or destination is not valid")
    return

  if not is_unblocked(grid, src[0], src[1]) or not is_unblocked(grid, dest[0], dest[1]):
    print("Source and destination are blocked")
    return

  if is_destination(src[0], src[1], dest):
    print("We are already at the destination")
    return

  closed_list = [[False for _ in range(COL)] for _ in range(ROW)]
  cell_details = [[Cell() for _ in range(COL)] for _ in range(ROW)]

  i = src[0]
  j = src[1]
  cell_details[i][j].f = 0
  cell_details[i][j].g = 0
  cell_details[i][j].h = 0
  cell_details[i][j].parent_i = i
  cell_details[i][j].parent_j = j

  open_list = []
  heapq.heappush(open_list, (0.0, i, j))

  found_dest = False

  while len(open_list) > 0:
    p = heapq.heappop(open_list)

    i = p[1]
    j = p[2]
    closed_list[i][j] = True

    directions = [(0, 1), (0, -1), (1, 0), (-1, 0), (1, 1), (1, -1), (-1, 1), (-1, -1)]
    for dir in directions:
      new_i = i + dir[0]
      new_j = j + dir[1]

      if is_valid(new_i, new_j) and is_unblocked(grid, new_i, new_j) and not closed_list[new_i][new_j]:
        if is_destination(new_i, new_j, dest):
          cell_details[new_i][new_j].parent_i = i
          cell_details[new_i][new_j].parent_j = j
          print("The destination cell is found")
          trace_path(cell_details, dest)
          found_dest = True
          return

        else:
          g_new =  cell_details[i][j].g + 1.0
          h_new = calculate_h_value(new_i, new_j, dest)
          f_new = g_new + h_new

          if cell_details[new_i][new_j].f == float('inf') or cell_details[new_i][new_j].f > f_new:
            heapq.heappush(open_list, (f_new, new_i, new_j))

            cell_details[new_i][new_j].f = f_new
            cell_details[new_i][new_j].g = g_new
            cell_details[new_i][new_j].h = h_new
            cell_details[new_i][new_j].parent_i = i
            cell_details[new_i][new_j].parent_j = j

  if not found_dest:
    print("Destination cell is not found")

def main():

  grid = [
      [1, 0, 1, 1, 1, 1, 0, 1, 1, 1],
      [1, 1, 1, 0, 1, 1, 1, 0, 1, 1],
      [1, 1, 1, 0, 1, 1, 0, 1, 0, 1],
      [0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
      [1, 1, 1, 0, 1, 1, 1, 0, 1, 0],
      [1, 0, 1, 1, 1, 1, 0, 1, 0, 0],
      [1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
      [1, 0, 1, 1, 1, 1, 0, 1, 1, 1],
      [1, 1, 1, 0, 0, 0, 1, 0, 0, 1]
  ]

  src = [8, 0]
  dest = [0, 0]

  a_star_search(grid, src, dest)

if __name__ == "__main__":
  main()

The destination cell is found
The Path is: 
-> (8, 0) -> (7, 0) -> (6, 0) -> (5, 0) -> (4, 1) -> (3, 2) -> (2, 1) -> (1, 0) -> (0, 0) 


# **Assignment - 5**

In [ ]:
import math

PLAYER_X = "X"
PLAYER_O = "O"
EMPTY = "."

def print_board(board):
  for row in board:
    print(" ".join(row))
  print()

def evaluate_board(board):
  for i in range(3):
    if board[i][0] == board[i][1] == board[i][2] != EMPTY:
      return 10 if board[i][0] == PLAYER_X else -10

    if board[0][i] == board[1][i] == board[2][i] != EMPTY:
      return 10 if board[0][i] == PLAYER_X else -10

  if board[0][0] == board[1][1] == board[2][2] != EMPTY:
      return 10 if board[0][0] == PLAYER_X else -10
  if board[0][2] == board[1][1] == board[2][0] != EMPTY:
      return 10 if board[0][2] == PLAYER_X else -10

  return 0

def is_game_over(board):
  return evaluate_board(board) != 0 or all(cell != EMPTY for row in board for cell in row)

def minmax(board, depth, is_maximising):
  score = evaluate_board(board)

  if score == 10 or score == -10:
    return score

  if is_game_over(board):
    return 0

  if is_maximising:
    best_score = -math.inf
    for i in range(3):
      for j in range(3):
        if board[i][j] == EMPTY:
          board[i][j] = PLAYER_X
          best_score = max(best_score, minmax(board, depth + 1, False))
          board[i][j] = EMPTY
    return best_score

  else:
    best_score = math.inf
    for i in range(3):
      for j in range(3):
        if board[i][j] == EMPTY:
          board[i][j] = PLAYER_O
          best_score = min(best_score, minmax(board, depth + 1, True))
          board[i][j] = EMPTY
    return best_score

def find_best_move(board):
  best_value = -math.inf
  best_move = (-1, -1)

  for i in range(3):
    for j in range(3):
        if board[i][j] == EMPTY:
          board[i][j] = PLAYER_X
          move_value = minmax(board, 0, False)
          board[i][j] = EMPTY

          if move_value > best_value:
            best_move = (i, j)
            best_value = move_value

  return best_move

def play_game():
  board = [[EMPTY for _ in range(3)] for _ in range(3)]
  print("Tic-Tac-Toe: Player X(You) vs. Player O(Computer).")
  print_board(board)

  while(True):
    row = int(input("Enter the row move(0, 1 or 2): "))
    col = int(input("Enter the column move(0, 1 or 2): "))

    if row not in (0, 1, 2) or col not in (0, 1, 2):
      print("Invalid input. Please enter 0, 1 or 2 for both row and column")
      continue

    if board[row][col] != EMPTY:
      print("Invalid move. Try again")
      continue

    board[row][col] = PLAYER_X

    if is_game_over(board):
      print_board(board)
      if evaluate_board(board) == 10:
        print("You win")
      else:
        print("It's a draw")
      break

    print("Computer's turn.....")
    best_move = find_best_move(board)
    board[best_move[0]][best_move[1]] = PLAYER_O

    print_board(board)
    if is_game_over(board):
      if evaluate_board(board) == -10:
        print("Computer win")
      else:
        print("It's a draw")
      break

if __name__ == "__main__":
  play_game()

Tic-Tac-Toe: Player X(You) vs. Player O(Computer).
. . .
. . .
. . .

Enter the row move(0, 1 or 2): 0
Enter the column move(0, 1 or 2): 0
Computer's turn.....
X O .
. . .
. . .

Enter the row move(0, 1 or 2): 0
Enter the column move(0, 1 or 2): 1
Invalid move. Try again
Enter the row move(0, 1 or 2): 1
Enter the column move(0, 1 or 2): 0
Computer's turn.....
X O O
X . .
. . .

Enter the row move(0, 1 or 2): 2
Enter the column move(0, 1 or 2): 0
X O O
X . .
X . .

You win


# **Assignment - 6**

In [2]:
N = int(input("Enter size of the chessboard: "))

def solveNQueens(board, col):

  if col == N:
    for row in board:
      print(row)
    return True

  for i in range(N):
    if isSafe(board, i, col):
      board[i][col] = 1

      if solveNQueens(board, col + 1):
        return True

    board[i][col] = 0
  return False

def isSafe(board, row, col):

  for x in range(col):
    if board[row][x] == 1:
      return False

  for x, y in zip(range(row, -1, -1), range(col, -1, -1)):
    if board[x][y] == 1:
      return False

  for x, y in zip(range(row, N, 1), range(col, -1, -1)):
    if board[x][y] == 1:
      return False

  return True

board = [[0 for x in range(N)] for y in range(N)]

if not solveNQueens(board, 0):
  print("Solution does not exist.")

Enter size of the chessboard: 2
Solution does not exist.


# **Assignment - 7**

In [ ]:
facts = ["A", "B"]

rules = [
    (["A", "B"], "C"),
    (["C"], "D"),
    (["D"], "E")
]

def forward_chaining(facts, rules):
  inferred = set(facts)
  new_fact_added = True

  while new_fact_added:
    new_fact_added = False
    for rule in rules:
      conditions, conclusions = rule

      all_conditions_met = True
      for condition in conditions:
        if condition not in inferred:
          all_conditions_met = False
          break


      if all_conditions_met and conclusions not in inferred:
        inferred.add(conclusions)
        print(f"Inferred new fact: {conclusions}")
        new_fact_added = True

  return inferred

print("Initial facts: ", facts)
inferred_facts = forward_chaining(facts, rules)
print("Final inferred facts: ", inferred_facts)

Initial facts:  ['A', 'B']
Inferred new fact: C
Inferred new fact: D
Inferred new fact: E
Final inferred facts:  {'D', 'C', 'E', 'A', 'B'}


# **Assignment - 8**

In [ ]:
facts = ["A", "B"]

rules = [
    (["A", "B"], "C"),
    (["C"], "D"),
    (["D"], "E")
]

def backward_chaining(goal, facts, rules):
  if goal in facts:
    print(f"Goal {goal} is already a fact.")
    return True

  for condition, conclusion in rules:
    if conclusion == goal:
      print(f"Trying to infer {goal} using the rule: {conclusion} -> {goal}.")

      all_conditions_met = True
      for cond in condition:
        if not backward_chaining(cond, facts, rules):
          all_conditions_met = False
          break

      if all_conditions_met:
        print(f"Goal {goal} inferred successfully.")
        return True

  print(f"Goal {goal} cannot be inferred.")
  return False

goal = str(input("Enter a goal to prove: ")).upper()
print(f"Trying to prove a goal: {goal}")
if backward_chaining(goal, facts, rules):
  print(f"Goal {goal} has been proven.")
else:
  print(f"Goal {goal} cannot be proven.")

Enter a goal to prove: a
Trying to prove a goal: A
Goal A is already a fact.
Goal A has been proven.


# **Assignment - 9**

In [ ]:
# Import necessary libraries
import re

# Define the Chatbot class
class Chatbot:
    def __init__(self):
        self.responses = {
            r"hello|hi|hey": "Hello! How can I assist you today?",
            r"what are your (working hours|hours of operation)\??": "Our working hours are from 9 AM to 9 PM, Monday to Saturday.",
            r"how can I contact you\??": "You can contact us at support@example.com or call us at +1-234-567-890.",
            r"where are you located\??": "We are located at 123 Main Street, Springfield.",
            r"thank you|thanks": "You're welcome! Let me know if you need further assistance.",
            r"bye|exit|quit": "Goodbye! Have a great day!",
        }
        self.default_response = "I'm sorry, I didn't understand that. Could you rephrase your question?"

    def get_response(self, user_input):
        for pattern, response in self.responses.items():
            if re.search(pattern, user_input, re.IGNORECASE):
                return response
        return self.default_response

# Function to start chatbot conversation
def start_chat():
    print("Welcome to the Customer Service Chatbot!")
    print("You can type 'bye' or 'exit' anytime to end the conversation.\n")
    chatbot = Chatbot()

    while True:
        user_input = input("You: ")
        if user_input.lower() in ["bye", "exit", "quit"]:
            print("Chatbot: Goodbye! Have a great day!")
            break
        response = chatbot.get_response(user_input)
        print(f"Chatbot: {response}")

# Run the chatbot
if __name__ == "__main__":
    start_chat()

# Practice

In [ ]:
# -------------------------------------------------------------------- #

In [ ]:
# -------------------------------------------------------------------- #

In [ ]:
# -------------------------------------------------------------------- #

In [ ]:
# -------------------------------------------------------------------- #

In [ ]:
# -------------------------------------------------------------------- #

In [ ]:
# -------------------------------------------------------------------- #

In [ ]:
# -------------------------------------------------------------------- #

In [ ]:
# -------------------------------------------------------------------- #

In [ ]:
# -------------------------------------------------------------------- #